baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Module 0"
theme = "teach"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
relativeURLs = true

[params]
	editURL = "https://github.com/sjmd/orientation/tree/master/content/"
	helpURL = "https://course.sjmd.space/help"
	description = "Social Justice, Minus Dogma Course Orientation"
	author = "Sam Killermann"
	showVisitedLinks = true
	disableBreadcrumb = false
	disableNextPrev = false
	themeVariant = ""

[outputs]
	home = [ "HTML", "RSS", "JSON"]
